***Task 01:***
**Scenario: You are managing game scores for a gaming application**

In [98]:
import numpy as np

In [101]:
#1. Create a NumPy array to store player names, game scores, and levels reached.
players=np.array([
    ["Talha",200,5],
    ["Durrab",350,7],
    ["Haris",99,3],
    ["Sheikh",88,1],
    ["Ali",350,8],
])
data=print("Array is :\n",players)

Array is :
 [['Talha' '200' '5']
 ['Durrab' '350' '7']
 ['Haris' '99' '3']
 ['Sheikh' '88' '1']
 ['Ali' '350' '8']]


In [103]:
#2. Update the score of the player who has reached the highest level.
level=players[:,2].astype(int)
max_level=np.argmax(level)
print(max_level)

players[max_level,1]=500
print(players)

4
[['Talha' '200' '5']
 ['Durrab' '350' '7']
 ['Haris' '99' '3']
 ['Sheikh' '88' '1']
 ['Ali' '500' '8']]


In [104]:
#3. Append a new player's data (name, score, level) to the array
new=["Zalaid",200,4]
players=np.vstack([players,new])
print(players)

[['Talha' '200' '5']
 ['Durrab' '350' '7']
 ['Haris' '99' '3']
 ['Sheikh' '88' '1']
 ['Ali' '500' '8']
 ['Zalaid' '200' '4']]


In [105]:
#4. Insert a new player's score at a specific index within the array.
index=5
players=np.insert(players,index,["Usama",499,9],axis=0)
print(players)

[['Talha' '200' '5']
 ['Durrab' '350' '7']
 ['Haris' '99' '3']
 ['Sheikh' '88' '1']
 ['Ali' '500' '8']
 ['Usama' '499' '9']
 ['Zalaid' '200' '4']]


In [106]:
#5. Delete the player with the lowest score from the dataset
score=players[:,1].astype(int)
mini=np.argmin(score)
print(mini)
players=np.delete(players,mini,axis=0)
print(players)

3
[['Talha' '200' '5']
 ['Durrab' '350' '7']
 ['Haris' '99' '3']
 ['Ali' '500' '8']
 ['Usama' '499' '9']
 ['Zalaid' '200' '4']]


***Task 02***
**Scenario: You are analyzing website traffic data.**

In [107]:
#1. Create two NumPy arrays: one for daily visitors and another for pages viewed.
visitors = np.array([120, 150, 90, 180, 210])
pages_viewed = np.array([80, 130, 75, 200, 110])
print(visitors)
print(pages_viewed)

[120 150  90 180 210]
[ 80 130  75 200 110]


In [108]:
#2. Create a shallow copy of the visitors array and a deep copy of the pages viewed array.
visitors_shallow = visitors.view()
pages_viewed_deep = pages_viewed.copy()
print(visitors_shallow)
print(pages_viewed_deep)

[120 150  90 180 210]
[ 80 130  75 200 110]


In [109]:
#3. Concatenate both arrays to form a new array.
combined_data = np.concatenate((visitors, pages_viewed))
print(combined_data)

[120 150  90 180 210  80 130  75 200 110]


In [110]:
#4. Split the concatenated array into two parts based on a threshold (e.g., more than 100 pages viewed).
below = combined_data[combined_data <= 100]
above = combined_data[combined_data > 100]
print(below)
print(above)

[90 80 75]
[120 150 180 210 130 200 110]


In [113]:
#5. Modify the original arrays and observe the changes in the copies.
visitors[0] = 300
pages_viewed[1] = 250
print(visitors)
print(pages_viewed)
print(visitors_shallow)
print(pages_viewed_deep)

[300 150  90 180 210]
[ 80 250  75 200 110]
[300 150  90 180 210]
[ 80 130  75 200 110]
